# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48a2fff3a530a03497d760967d8b90f1ba7c2dd91082d2efc679646bd22ea8be8368717fdec038c618e993066f9e69e77d92aa0a70123eca628625c549e073fa

test:
  secret_key_base: b6d220d8e68e8004d27ca5ae5ce14aa530672e959efd2feed5024e3f8cb26bf77348bbb38b8f6080970056382202d230fcc86e29e18f1190470d1cda1c6702c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
